version: "3"

services:
  web:
    build: ./django/
    restart: always
    env_file: .env
    command: ["/code/docker-entrypoint.sh"]
    volumes:
      - ./django:/code
      - /usr/src/app
      - /usr/src/app/static
    environment:
      DEBUG: 'true'
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:9.6-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data/

  nginx:
    build: ./nginx/
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /www/static
      - /usr/src/app
      - /usr/src/app/static

volumes:
  dbdata:
