version: "3"

services:
  web:
    build: ./django/
    restart: always
    env_file: .env
    command: ["/code/docker-entrypoint.sh"]
    environment:
      DEBUG: 'true'
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - "./django:/code"

  client:
    build: ./angular
    command: ["npm", "start"]
    ports:
      - "4200:4200"
    volumes:
      - "./angular:/usr/src/app"

  db:
    image: postgres:9.6-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data/"

  nginx:
    build: ./nginx/
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./angular/dist:/usr/src/app"
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"

volumes:
  dbdata:
