version: "3"

services:
  web:
    build: ./django/
    restart: always
    env_file: .env
    command: ["/code/docker-entrypoint.sh"]
    environment:
      DEBUG: 'true'
    ports:
      - "8000"
    depends_on:
      - db

  client:
    build: ./angular
    volumes:
      - "appdata:/usr/src/app"

  db:
    image: postgres:9.6-alpine
    restart: always
    ports:
      - "5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data/"

  nginx:
    build: ./nginx/
    restart: always
    ports:
      - "80:80"
    volumes:
      - "appdata:/usr/src/app"

volumes:
  dbdata:
  appdata:
